#:schema node_modules/wrangler/config-schema.json
name = "clearsky-static-ui"
compatibility_date = "2024-11-12"
assets = { directory = "./static" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
